name: 'Hello World'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - name: Date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "YYYY_MM_DD HH_mm_ss_SSS"

